make:
	gcc -o mapreduce-executable mapreduce.c mr_functions.c mapreduce.h -Wall -Werror -pthread -g
object:
	gcc -c mapreduce.c mr_functions.c mapreduce.h -Wall -Werror -pthread
clean:
	rm -f mapreduce-executable
